### ISSUE TITLE
NPM install fails - no npm registry

### ISSUE THREAD

**Issue by tremendus** [trailsjs/trailpack-express4#2] opened 2016-02-19 00:30 UTC
Doing a new install per the guide https://github.com/trailsjs/trails 

after `yo install` npm throws an error installing trailpack-express4

```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install" "trailpack-express4@latest" "--save"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/trailpack-express4
npm ERR! 404 
npm ERR! 404 'trailpack-express4' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

a manual install of the npm also fails with 404

**Comment by maissani** [comment] 2016-02-19 02:07
Hi tremens,

**The following response is not official but should be clarify what happens**
## The origin of the error and how to reproduce
I have reproduce the install with 
> yo trails

Chosing the express4 option please stop me if i am wrong

## What's happen
Durring yeoman installation of packages you noticed that trail pack-express4 is missing from npm registry. 
This is not a bug, trailpack-express4 is not in npm registry at the moment , until a beta / Alpha or dev will be posted @ npmjs.com
You can check that there is not package at the moment : https://www.npmjs.com/search?q=trailpack-express4.
I think this package will be available in a short amount of time. 
## What you should do
3 options: 
* First One: Wait until trailpack-express4 will be released
* Second: Fallback to Hapi until trailpack-express4 will be released then change your methods as soon as it has been release

**Comment by jaumard** [comment] 2016-02-19 11:44
@tjwebb maybe we can add "not available yet" on "work in progress" for express4 on the generator ? Or just put trailpack-express4 on npm as alpha version (my PR is waiting ;)) ? Like this we can have some feedback about it.

**Comment by tjwebb** [comment] 2016-02-28 03:01
@jaumard I'll send up a PR so that travisci will autodeploy tagged versions to npm. That way you can manage releases however you'd like. sound good?

**Comment by jaumard** [comment] 2016-02-28 10:05
Thanks @tjwebb I wanted to know if it's ok for you to deploy my version on npm. I just tried to deploy alpha1 release but it seems like the travis configuration is not ok. Look here https://travis-ci.org/trailsjs/trailpack-express4/jobs/112376332 

```
Deploying application
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
~/.npmrc size: 48
npm ERR! publish Failed PUT 401
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v5.6.0/bin/node" "/home/travis/.nvm/versions/node/v5.6.0/bin/npm" "publish"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code E401
npm ERR! You must be logged in to publish packages : trailpack-express4
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/trailsjs/trailpack-express4/npm-debug.log
```

**Comment by jaumard** [comment] 2016-03-01 11:10
@tremendus now `trailpack-express4` is on npm.

**Closed by jaumard** 2016-03-01 11:10 UTC
